coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: false

# post coverage report as comment on PR
comment:
  require_changes: true

# enable codecov to report to GitHub status checks
github_checks:
  annotations: true

# paths to ignore
ignore:
  - ".github/"
  - "build_tools/"
  - "docs/"
