repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: name-tests-test
        args: ["--django"]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.4.2]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        files: predictably-core/
        args: [--strict, --ignore-missing-imports]
        exclude: |
          (?x)(
              /tests/|
              docs/source
          )
        additional_dependencies: []

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [".[toml]"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
        additional_dependencies:
          - tomli

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: ["--max-line-length=88", "--config=pyproject.toml", "docs"]
        additional_dependencies: ["tomli"]

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
      - id: numpydoc-validation
        exclude: |
          (?x)(
              /tests/|
              predictably_core/core/_pprint/|
              docs/source|
              setup.py
          )
